services:
  redis:
    image: redis:7.2-alpine
    container_name: jstratusd-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--maxmemory",
        "100mb",
        "--maxmemory-policy",
        "noeviction"
      ]
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 150M
    networks:
      - default

  upload-service:
    build:
      context: ./Upload-Service
      dockerfile: Dockerfile
    container_name: jstratusd-upload-service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8081

      REDIS_PORT: 6379
      REDIS_SSL_ENABLED: false
      UPSTASH_REDIS_REST_HOST: redis
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN:-}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      EUREKA: http://service-discovery:8761/eureka/

      CONTAINER_APP_HOSTNAME: upload-service

      JAVA_OPTS: "-Xms128m -Xmx256m -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC -Xss512k"

    depends_on:
      - redis

    ports:
      - "8081:8081"

    deploy:
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 300M

    networks:
      - default
      - gateway-network

  deploy-service:
    build:
      context: ./Deploy-Service
      dockerfile: Dockerfile
    container_name: jstratusd-deploy-service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8082

      REDIS_PORT: 6379
      REDIS_SSL_ENABLED: false
      UPSTASH_REDIS_REST_HOST: redis
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN:-}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      EUREKA: http://service-discovery:8761/eureka/

      WORKER_WEBSITE_URL: http://deploy-service

      CONTAINER_APP_HOSTNAME: deploy-service

      JAVA_OPTS: "-Xms256m -Xmx400m -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC -Xss512k"

    depends_on:
      - redis

    ports:
      - "8082:8082"

    deploy:
      resources:
        limits:
          memory: 1400M
        reservations:
          memory: 800M

    networks:
      - default
      - gateway-network

volumes:
  redis-data:

networks:
  gateway-network:
    external: true
    name: gateway-discovery-auth_symptom-network